OganicShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('jet/', include('jet.urls')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('', include('main2.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main2/urls.py
from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('search', views.search, name='search'),
    path('filter-data', views.filter_data, name='filter_data'),
    path('categories-list', views.categories_list, name='categories-list'),
    path('brands-list', views.brands_list, name='brands-list'),
    path('products-list', views.products_list, name='products-list'),
    path('categories-products-list/<int:cate_id>', views.category_product_list, name='categories-product-list'),
    path('brands-products-list/<int:brand_id>', views.brand_product_list, name='brands-product-list'),
    path('product/<str:slug>/<int:id>', views.product_detail, name='product_detail'),
    path('load-more-data', views.load_more_data, name='load_more_data'),
    path('add-to-cart',views.add_to_cart,name='add_to_cart'),
    path('cart',views.cart_list,name='cart'),
    path('delete-from-cart',views.delete_cart_item,name='delete-from-cart'),
    # path('delete-all-cart',views.delete_all_cart_item,name='delete-all-cart'),
    path('update-cart',views.update_cart_item,name='update-cart'),
    path('accounts/signup',views.signup,name='signup'),
    path('checkout',views.checkout,name='checkout'),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment-done/', views.payment_done, name='payment_done'),
    path('payment-cancelled/', views.payment_canceled, name='payment_cancelled'),
    path('save-review/<int:pid>', views.save_review, name='save-review'),
    path('my-dashboard', views.my_dashboard, name='my_dashboard'),
    path('my-orders', views.my_orders, name='my_orders'),
    path('my-orders-items/<int:id>', views.my_order_items, name='my_order_items'),
    path('add-wishlist', views.add_wishlist, name='add_wishlist'),
    path('my-wishlist', views.my_wishlist, name='my_wishlist'),
    path('my-reviews', views.my_reviews, name='my-reviews'),
    path('my-addressbook', views.my_addressbook, name='my-addressbook'),
    path('add-address', views.save_address, name='add-address'),
    path('activate-address', views.activate_address, name='activate-address'),
    path('update-address/<int:id>', views.update_address, name='update-address'),
    path('edit-profile', views.edit_profile, name='edit-profile'),
    path('cancel-order', views.cancel_order, name='cancel-order'),
    path('statical', views.statical, name='statical-order'),
    path('statical1', views.statical1, name='statical1-order'),
    # path('admin/email', views.send_mail1, name='cancel-test'),
    # path('send-mail', views.send_mail1, name='eseeee-profile'),

]

main2/models.py
from django.db import models
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User

class Banner(models.Model):
    img = models.CharField(max_length=255)
    alt_text = models.CharField(max_length=300)
# Create your models here.

class Category(models.Model):
    category_name = models.CharField(max_length=255)
    image = models.ImageField(upload_to="cat_imgs/")

    def image_tag(self):
        return mark_safe(f'<img src={self.image.url} width="50px" height="50px" />')
    def __str__(self):
        return self.category_name


class Brand(models.Model):
    brand_name = models.CharField(max_length=255)
    image = models.ImageField(upload_to="brand_imgs/")

    def image_tag(self):
        return mark_safe(f'<img src={self.image.url} width="50px" height="50px" />')

    def __str__(self):
        return self.brand_name


class Size(models.Model):
    size_name = models.CharField(max_length=255)

    def __str__(self):
        return self.size_name


class Product(models.Model):
    product_name = models.CharField(max_length=255)
    image = models.ImageField(upload_to="product_imgs/")
    slug = models.CharField(max_length=255)
    sku = models.CharField(max_length=255)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    is_special = models.BooleanField(default=False)

    def image_tag(self):
        return mark_safe(f'<img src={self.image.url} width="50px" height="50px" />')
    def __str__(self):
        return self.product_name


class ProductAttribute(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    price = models.PositiveIntegerField()
    qty = models.IntegerField()

    def __str__(self):
        return self.product.product_name
status_choice=(
        ('Waiting Payment','waiting'),
        ('Ready to ship','ready'),
        ('Shipped','shipped'),
        ('Complete','complete'),
        ('Cancel','cancel'),)
class CartOrder(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    total_amt=models.FloatField()
    paid_status=models.BooleanField(default=False)
    order_dt=models.DateTimeField(auto_now_add=True)
    order_status=models.CharField(choices=status_choice,default='Waiting Payment',max_length=150)
    qty = models.IntegerField(null=True)
    qty_remaining = models.IntegerField(null=True)
    class Meta:
        verbose_name_plural='Orders'

class CartOrderItems(models.Model):
    order=models.ForeignKey(CartOrder,on_delete=models.CASCADE)
    invoice_no=models.CharField(max_length=150)
    item=models.CharField(max_length=150)
    image=models.CharField(max_length=200)
    qty=models.IntegerField()
    price=models.FloatField()
    total=models.FloatField()

    class Meta:
        verbose_name_plural='Order Items'

    def image_tag(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" />' % (self.image))


RATING=(
    (1,'1'),
    (2,'2'),
    (3,'3'),
    (4,'4'),
    (5,'5'),
)
class ProductReview(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    review_text=models.TextField()
    review_rating=models.CharField(choices=RATING,max_length=150)

    class Meta:
        verbose_name_plural='Reviews'

    def get_review_rating(self):
        return self.review_rating

# WishList
class Wishlist(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural='Wishlist'

# AddressBook
class UserAddressBook(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    mobile=models.CharField(max_length=50,null=True)
    address=models.TextField()
    status=models.BooleanField(default=False)

    class Meta:
        verbose_name_plural='AddressBook'

main2/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.db.models import Min, Max, Avg, Count
from django.db.models.functions import ExtractMonth
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.core import serializers
from .models import Category, Brand, Product, Size, ProductAttribute, CartOrder, CartOrderItems, UserAddressBook, \
    ProductReview, Wishlist
from main2.forms import SignupForm, ReviewAdd, ProfileForm, AddressBookForm
from django.urls import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm
from django.core.mail import EmailMessage, send_mail, send_mass_mail
from django.forms.models import model_to_dict

# Create your views here.
def home(request):
    data = Product.objects.filter(is_special=True).order_by('-id')
    cate = Category.objects.all()
    brand = Brand.objects.all()
    return render(request, 'index.html', {'data': data, 'cate': cate, 'brand': brand})


def categories_list(request):
    data = Category.objects.all()
    return render(request, 'categories.html', {"data": data})


def brands_list(request):
    data = Brand.objects.all()
    return render(request, 'brands.html', {"data": data})


def products_list(request):
    total_data = Product.objects.count()
    data = Product.objects.all().order_by('-id')[:6]
    min_price = ProductAttribute.objects.aggregate(Min('price'))
    max_price = ProductAttribute.objects.aggregate(Max('price'))
    return render(request, 'products.html',
                  {"data": data,
                   'total_data': total_data,
                   "min_price": min_price,
                   "max_price": max_price})


def category_product_list(request, cate_id):
    cate = Category.objects.get(id=cate_id)
    data = Product.objects.filter(category=cate)
    return render(request, 'category_product_list.html', {"data": data, "cate": cate})


def brand_product_list(request, brand_id):
    bra = Brand.objects.get(id=brand_id)
    data = Product.objects.filter(brand=bra)
    return render(request, 'brand_product_list.html', {"data": data, "bra": bra})


def product_detail(request, slug, id):
    product = Product.objects.get(id=id)
    attribute = ProductAttribute.objects.filter(product=product)
    related_products = Product.objects.filter(category=product.category).exclude(id=id)[:4]
    sizes = ProductAttribute.objects.filter(product=product).values('size_id', 'size__size_name', 'price').distinct()
    reviewForm = ReviewAdd()

    # Check
    canAdd = True
    reviewCheck = ProductReview.objects.filter(user=request.user, product=product).count()
    if request.user.is_authenticated:
        if reviewCheck > 0:
            canAdd = False
    # End

    # Fetch reviews
    reviews = ProductReview.objects.filter(product=product)
    # End

    # Fetch avg rating for reviews
    avg_reviews = ProductReview.objects.filter(product=product).aggregate(avg_rating=Avg('review_rating'))
    # End

    return render(request, 'product_detail.html',
                  {'data': product, 'attribute': attribute, 'related': related_products, 'sizes': sizes,
                   'reviewForm': reviewForm,
                   'canAdd': canAdd, 'reviews': reviews, 'avg_reviews': avg_reviews})


def search(request):
    q = request.GET['q']
    data = Product.objects.filter(product_name__icontains=q).order_by('-id')
    return render(request, 'search.html', {'data': data})


def filter_data(request):
    categories = request.GET.getlist('category[]')
    brands = request.GET.getlist('brand[]')
    sizes = request.GET.getlist('size[]')
    minPrice = request.GET['minPrice']
    maxPrice = request.GET['maxPrice']
    allProducts = Product.objects.all().order_by('-id').distinct()
    allProducts = allProducts.filter(productattribute__price__gte=minPrice)
    allProducts = allProducts.filter(productattribute__price__lte=maxPrice)
    if len(categories) > 0:
        allProducts = allProducts.filter(category__id__in=categories).distinct()
    if len(brands) > 0:
        allProducts = allProducts.filter(brand__id__in=brands).distinct()
    if len(sizes) > 0:
        allProducts = allProducts.filter(productattribute__size__id__in=sizes).distinct()
    t = render_to_string('ajax/product-list.html', {'data': allProducts})
    return JsonResponse({'data': t})


def load_more_data(request):
    offset = int(request.GET['offset']) + 6
    limit = int(request.GET['limit'])
    data = Product.objects.all().order_by('-id')[offset:offset + limit]
    t = render_to_string('ajax/product-list.html', {'data': data})
    return JsonResponse({'data': t})


def add_to_cart(request):
    # del request.session['cartdata']
    cart_p = {}
    attribute = ProductAttribute.objects.get(product_id=request.GET['id'], price=request.GET['price'])
    cart_p[str(request.GET['id']) + str(attribute.size.size_name)] = {
        'image': request.GET['image'],
        'title': request.GET['title'],
        'qty': request.GET['qty'],
        'price': request.GET['price'],
        'attribute': attribute.size.size_name,
        'qty_max': attribute.qty
    }
    if 'cartdata' in request.session:
        if str(str(request.GET['id']) + str(attribute.size.size_name)) in request.session['cartdata']:
            cart_data = request.session['cartdata']
            cart_data[str(request.GET['id']) + str(attribute.size.size_name)]['qty'] = int(
                cart_p[str(request.GET['id']) + str(attribute.size.size_name)]['qty'])
            cart_data.update(cart_data)
            request.session['cartdata'] = cart_data
        else:
            cart_data = request.session['cartdata']
            cart_data.update(cart_p)
            request.session['cartdata'] = cart_data
    else:
        request.session['cartdata'] = cart_p
    return JsonResponse({'data': request.session['cartdata'], 'totalitems': len(request.session['cartdata'])})


def cart_list(request):
    total_amt = 0
    if 'cartdata' in request.session:
        for p_id, item in request.session['cartdata'].items():
            total_amt += int(item['qty']) * float(item['price'])
        return render(request, 'cart.html',
                      {'cart_data': request.session['cartdata'], 'totalitems': len(request.session['cartdata']),
                       'total_amt': total_amt})
    else:
        return render(request, 'cart.html', {'cart_data': '', 'totalitems': 0, 'total_amt': total_amt})


def delete_cart_item(request):
    p_id = str(request.GET['id'])
    if 'cartdata' in request.session:
        if p_id in request.session['cartdata']:
            cart_data = request.session['cartdata']
            del request.session['cartdata'][p_id]
            request.session['cartdata'] = cart_data
    total_amt = 0
    for p_id, item in request.session['cartdata'].items():
        total_amt += int(item['qty']) * float(item['price'])
    t = render_to_string('ajax/cart-list.html',
                         {'cart_data': request.session['cartdata'], 'totalitems': len(request.session['cartdata']),
                          'total_amt': total_amt})
    return JsonResponse({'data': t, 'totalitems': len(request.session['cartdata'])})


def update_cart_item(request):
    p_id = str(request.GET['id'])
    p_qty = request.GET['qty']
    if 'cartdata' in request.session:
        if p_id in request.session['cartdata']:
            cart_data = request.session['cartdata']
            cart_data[str(request.GET['id'])]['qty'] = p_qty
            request.session['cartdata'] = cart_data
    total_amt = 0
    for p_id, item in request.session['cartdata'].items():
        total_amt += int(item['qty']) * float(item['price'])
    t = render_to_string('ajax/cart-list.html',
                         {'cart_data': request.session['cartdata'], 'totalitems': len(request.session['cartdata']),
                          'total_amt': total_amt})
    return JsonResponse({'data': t, 'totalitems': len(request.session['cartdata'])})


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            pwd = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=pwd)
            login(request, user)
            return redirect('home')
    form = SignupForm
    return render(request, 'registration/signup.html', {'form': form})


@login_required
def checkout(request):
    total_amt = 0
    totalAmt = 0
    if 'cartdata' in request.session:
        for p_id, item in request.session['cartdata'].items():
            totalAmt += int(item['qty']) * float(item['price'])
        # Order
        order = CartOrder.objects.create(
            user=request.user,
            total_amt=totalAmt
        )
        # End
        for p_id, item in request.session['cartdata'].items():
            total_amt += int(item['qty']) * float(item['price'])
            # OrderItems
            CartOrderItems.objects.create(
                order=order,
                invoice_no='INV-' + str(order.id),
                item=item['title'],
                image=item['image'],
                qty=item['qty'],
                price=item['price'],
                total=float(item['qty']) * float(item['price'])
            )
        # End
        # Process Payment
        host = request.get_host()
        paypal_dict = {
            'business': settings.PAYPAL_RECEIVER_EMAIL,
            'amount': total_amt,
            'item_name': 'OrderNo-1' + str(order.id),
            'invoice': 'INV-1' + str(order.id),
            'currency_code': 'USD',
            'notify_url': 'http://{}{}'.format(host, reverse('paypal-ipn')),
            'return_url': 'http://{}{}'.format(host, reverse('payment_done')),

main2/templates/user/add-address.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Address Book <a href="{% url 'add-address' %}" class="float-right btn btn-sm btn-success"><i class="fa fa-plus"></i></a></h3>
	<div class="row">
		<div class="col-md-3">
			{% include 'user/user-sidebar.html' %}
		</div>
		<div class="col-md-9">
			{% if msg %}
			<p class="text-success">{{msg}}</p>
			{% endif %}
			<table class="table table-bordered">
				<form method="post">
					{% csrf_token %}
					{{form.as_table}}
					<tr>
						<td colspan="2">
							<input type="submit" value="Save" class="btn btn-primary" />
						</td>
					</tr>
				</form>
			</table>
		</div>
	</div>
</main>
{% endblock %}

main2/templates/user/addressbook.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Address Book <a href="{% url 'add-address' %}" class="float-right btn btn-sm btn-success"><i class="fa fa-plus"></i></a></h3>
	<div class="row">
		<div class="col-md-3">
			{% include 'user/user-sidebar.html' %}
		</div>
		<div class="col-md-9">
			<div class="row">
				{% for add in addbook %}
				<div class="col-md-4">
					<div class="card mb-3 {% if add.status %}border-secondary shadow{% endif %} address{{add.id}} address">
						<div class="card-body">
							<p class="card-text">{{add.address}}</p>
							<p class="card-text">{{add.mobile}}</p>
						</div>
						{% if add.status %}
						<div class="card-footer">
							<i class="fa fa-check-circle text-success check{{add.id}} check"></i>
							<button style="display:none;" data-address="{{add.id}}" class="btn btn-sm btn-info activate-address btn{{add.id}} actbtn">Activate</button>
							<a href="{% url 'update-address' add.id %}" class="float-right"><i class="fa fa-edit"></i></a>
						</div>
						{% else %}
						<div class="card-footer footer{{add.id}}">
							<i style="display:none;" class="fa fa-check-circle text-success check{{add.id}} check"></i>
							<button data-address="{{add.id}}" class="btn btn-sm btn-info activate-address btn{{add.id}} actbtn">Activate</button>
							<a href="{% url 'update-address' add.id %}" class="float-right"><i class="fa fa-edit"></i></a>
						</div>
						{% endif %}
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
</main>
{% endblock %}

main2/templates/user/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">My Dashboard</h3>
	<div class="row">
		<div class="col-md-3">
			{% include 'user/user-sidebar.html' %}
		</div>
		<div class="col-md-9">
			<div>
			  <canvas id="myChart"></canvas>
			</div>
		</div>
	</div>
</main>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script type="text/javascript">
	const labels = {{monthNumber|safe}};
	const data = {
	  labels: labels,
	  datasets: [{
	    label: 'Orders By Month',
	    backgroundColor: 'rgb(255, 99, 132)',
	    borderColor: 'rgb(255, 99, 132)',
	    data: {{totalOrders}},
	  }]
	};

	const config = {
	  type: 'bar',
	  data,
	  options: {}
	};

	var myChart = new Chart(
	    document.getElementById('myChart'),
	    config
  	);

</script>

{% endblock %}

main2/templates/user/edit-profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Edit Profile</h3>
	<div class="row">
		<div class="col-md-3">
			{% include 'user/user-sidebar.html' %}
		</div>
		<div class="col-md-9">
			{% if msg %}
			<p class="text-success">{{msg}}</p>
			{% endif %}
			<table class="table table-bordered">
				<form method="post">
					{% csrf_token %}
					{{form.as_table}}
					<tr>
						<td colspan="2">
							<input type="submit" value="Save" class="btn btn-primary" />
						</td>
					</tr>
				</form>
			</table>
		</div>
	</div>
</main>
{% endblock %}

main2/templates/user/order-items.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Order Items</h3>
	<div class="row">
		<div class="col-md-3">
			{% include 'user/user-sidebar.html' %}
		</div>
		<div class="col-md-9">
			<div class="table-responsive">
				<table class="table-bordered table">
					<thead>
						<tr>
							<th>Inv no</th>
							<th>Item</th>
							<th>Qty</th>
							<th>Price</th>
							<th>Total</th>
						</tr>
					</thead>
					<tbody>
						{% for item in orderitems %}
						<tr>
							<td>{{item.invoice_no}}</td>
							<td>
								<p><img src="/media/{{item.image}}" width="80" /></p>
								{{item.item}}
							</td>
							<td>{{item.qty}}</td>
							<td>{{item.price}}</td>
							<td>{{item.total}}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</main>
{% endblock %}

main2/templates/user/orders.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">My Orders</h3>
	<div class="row">
		<div class="col-md-3">
			{% include 'user/user-sidebar.html' %}
		</div>
		<div class="col-md-9">
			<div class="table-responsive">
				<table class="table-bordered table">
					<thead>
						<tr>
							<th>OrderNo</th>
							<th>Total Amt</th>
                            <th>Paid</th>
							<th>Status</th>
							<th>Order Time</th>
                            <th>Cancel</th>
						</tr>
					</thead>
					<tbody>
						{% for order in orders %}
						<tr>
							<td><a href="{% url 'my_order_items' order.id %}" class="btn btn-sm btn-dark">{{order.id}}</a></td>
							<td>{{order.total_amt}}</td>
                            <td>{{order.paid_status}}</td>
							<td>{{order.order_status}}</td>
							<td>{{order.order_dt}}</td>
                        {% if order.order_status != 'Complete' and order.order_status != 'Cancel'  %}
                           <td> <button class="btn btn-sm btn-danger cancel-order" data-order="{{order.id}}"><i class="fa fa-trash"></i></button></td>
                            {% else %}
                            <td></td>
                        {% endif %}
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</main>
{% endblock %}

main2/templates/user/reviews.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Reviews Items</h3>
	<div class="row">
		<div class="col-md-3">
			{% include 'user/user-sidebar.html' %}
		</div>
		<div class="col-md-9">
			<div class="table-responsive">
				<table class="table-bordered table">
					<thead>
						<tr>
							<th>Title</th>
							<th>Image</th>
							<th>Price</th>
							<th>ReviewText</th>
							<th>ReviewRating</th>
						</tr>
					</thead>
					<tbody>
						{% for review in reviews %}
						<tr>
							<td><a href="/product/{{review.product.slug}}/{{review.product.id}}">{{review.product.product_name}}</a></td>
							<td>
								<img width="100" src="/media/{{review.product.image}}" alt="{{review.product.product_name}}">
							</td>
							<td>{{review.product.productattribute_set.first.price}}</td>
							<td>{{review.review_text}}</td>
                            <td>{{review.review_rating}} <i class="fa fa-star text-warning"></i></td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</main>
{% endblock %}

main2/templates/user/update-address.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Update Address Book <a href="{% url 'add-address' %}" class="float-right btn btn-sm btn-success"><i class="fa fa-plus"></i></a></h3>
	<div class="row">
		<div class="col-md-3">
			{% include 'user/user-sidebar.html' %}
		</div>
		<div class="col-md-9">
			{% if msg %}
			<p class="text-success">{{msg}}</p>
			{% endif %}
			<table class="table table-bordered">
				<form method="post">
					{% csrf_token %}
					{{form.as_table}}
					<tr>
						<td colspan="2">
							<input type="submit" value="Save" class="btn btn-primary" />
						</td>
					</tr>
				</form>
			</table>
		</div>
	</div>
</main>
{% endblock %}

main2/templates/user/user-sidebar.html
<div class="list-group">
	<a href="{% url 'my_dashboard' %}" class="list-group-item {% if request.path == '/my-dashboard' %}active {% endif %}">Dashboard</a>
	<a href="{% url 'edit-profile' %}" class="list-group-item {% if request.path == '/edit-profile' %}active {% endif %}">Profile</a>
	<a href="{% url 'my_orders' %}" class="list-group-item {% if request.path == '/my-orders' %}active {% endif %}">Orders</a>
	<a href="{% url 'my_wishlist' %}" class="list-group-item {% if request.path == '/my-wishlist' %}active {% endif %}">Wishlist</a>
	<a href="{% url 'my-reviews' %}" class="list-group-item {% if request.path == '/my-reviews' %}active {% endif %}">My Reviews</a>
	<a href="{% url 'my-addressbook' %}" class="list-group-item {% if request.path == '/my-addressbook' %}active {% endif %}">Address Book</a>
	<a href="{% url 'password_change' %}" class="list-group-item {% if request.path == '/accounts/password_change/' %}active {% endif %}">Password Change</a>
	<a href="{% url 'logout' %}" class="text-danger list-group-item">Logout</a>
</div>

main2/templates/user/wishlist.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Wishlist Items</h3>
	<div class="row">
		<div class="col-md-3">
			{% include 'user/user-sidebar.html' %}
		</div>
		<div class="col-md-9">
			<div class="table-responsive">
				<table class="table-bordered table">
					<thead>
						<tr>
							<th>Product Name</th>
							<th>Image</th>
							<th>Price</th>
						</tr>
					</thead>
					<tbody>
						{% for wl in wlist %}
						<tr>
							<td><a href="/product/{{wl.product.slug}}/{{wl.product.id}}">{{wl.product.product_name}}</a></td>
							<td>
								<img width="100" src="/media/{{wl.product.image}}" alt="{{wl.product.product_name}}">
							</td>
							<td>{{wl.product.productattribute_set.first.price}}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</main>
{% endblock %}